apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: memcacheds.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: Memcached
    listKind: MemcachedList
    plural: memcacheds
    singular: memcached
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Memcached is the Schema for the memcacheds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MemcachedSpec defines the desired state of Memcached
          properties:
            size:
              description: Size is the size of the memcached deployment, SIZE , SIZE,
                SIZE!
              format: int32
              type: integer
          required:
          - size
          type: object
        status:
          description: MemcachedStatus defines the observed state of Memcached
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
        syncInterval:
          description: DNS interval
          properties:
            interval:
              description: External-dns sync interval to update etcd backend of coredns
              format: int32
              type: integer
          required:
          - interval
          type: object
        ttl:
          description: MemcachedDnsTTL defines the ...
          properties:
            ttl:
              description: How many seconds a resolver is supposed to cache DNS records
              format: int32
              type: integer
          required:
          - ttl
          type: object
        txtExpiration:
          description: MemcachedSplitBrainThreshold defines the split brain threshold
          properties:
            threshold:
              description: Defines split brain threshold in minutes
              format: int32
              type: integer
          required:
          - threshold
          type: object
      required:
      - txtExpiration
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
